create table if not exists public.form_unidades (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  ordem integer not null default 0,
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists idx_form_unidades_ativo_ordem
  on public.form_unidades (ativo, ordem, nome);

insert into public.form_unidades (nome, ordem, ativo)
values
  ('Examina Filial', 10, true),
  ('Examina Matriz', 20, true),
  ('Radiologica General Osório', 30, true),
  ('Radiologica Olaria', 40, true),
  ('Unimed', 50, true),
  ('CD', 60, true)
on conflict (nome) do update
set ordem = excluded.ordem,
    ativo = excluded.ativo;
