create table if not exists public.informatica_gestao_permissoes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  email text not null unique,
  nome text null,
  ativo boolean not null default true
);

insert into public.informatica_gestao_permissoes (email, nome, ativo)
values ('informatica@radiologica.com.br', 'Informática', true)
on conflict (email) do update
set ativo = excluded.ativo;

alter table if exists public.trocas_ativos
  add column if not exists glpi_tag text null,
  add column if not exists glpi_atualizado_em timestamptz null,
  add column if not exists glpi_atualizado_por text null;

alter table if exists public.instalacoes_ativos
  add column if not exists glpi_tag text null,
  add column if not exists glpi_atualizado_em timestamptz null,
  add column if not exists glpi_atualizado_por text null;

create index if not exists idx_trocas_ativos_glpi_tag on public.trocas_ativos (glpi_tag);
create index if not exists idx_instalacoes_ativos_glpi_tag on public.instalacoes_ativos (glpi_tag);

create or replace view public.vw_gestao_equipamentos as
select
  'troca'::text as origem,
  t.id::bigint as registro_id,
  t.created_at,
  t.nome_tecnico,
  t.tecnico_user_id,
  t.tipo_ativo,
  t.unidade,
  t.setor,
  t.nome_ativo_antigo,
  t.nome_ativo_novo as nome_equipamento,
  t.ip_ativo_antigo,
  t.ip_ativo_novo as ip_equipamento,
  t.modelo_ativo_antigo,
  t.modelo_ativo_novo as modelo_equipamento,
  t.motivo_troca as observacoes,
  t.programas_instalados,
  coalesce(t.status_glpi, 'pendente') as status_glpi,
  t.glpi_tag,
  t.glpi_atualizado_em,
  t.glpi_atualizado_por
from public.trocas_ativos t

union all

select
  'instalacao'::text as origem,
  i.id::bigint as registro_id,
  i.created_at,
  i.nome_tecnico,
  i.tecnico_user_id,
  i.tipo_ativo,
  i.unidade,
  i.setor,
  null::text as nome_ativo_antigo,
  i.nome_ativo_novo as nome_equipamento,
  null::text as ip_ativo_antigo,
  i.ip_ativo_novo as ip_equipamento,
  null::text as modelo_ativo_antigo,
  i.modelo_ativo_novo as modelo_equipamento,
  i.observacoes_instalacao as observacoes,
  i.programas_instalados,
  coalesce(i.status_glpi, 'pendente') as status_glpi,
  i.glpi_tag,
  i.glpi_atualizado_em,
  i.glpi_atualizado_por
from public.instalacoes_ativos i;
