create table if not exists public.instalacoes_ativos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  tecnico_user_id uuid not null,
  nome_tecnico text not null,
  tipo_ativo text not null check (tipo_ativo in ('Computador', 'Monitor', 'Impressora', 'Tablet')),
  nome_ativo_novo text not null,
  ip_ativo_novo text null,
  modelo_ativo_novo text null,
  programas_instalados text[] not null default array[]::text[],
  setor text not null,
  unidade text not null,
  observacoes_instalacao text not null,
  status_glpi text not null default 'pendente'
);

create index if not exists idx_instalacoes_ativos_created_at on public.instalacoes_ativos (created_at desc);
create index if not exists idx_instalacoes_ativos_tecnico_user_id on public.instalacoes_ativos (tecnico_user_id);
create index if not exists idx_instalacoes_ativos_status_glpi on public.instalacoes_ativos (status_glpi);
